### ISSUE TITLE
Script load failed

### ISSUE THREAD

**Issue by anufryieu** [Jamling/hexo-site#3]
I download yesterday hexo site from your master branch and nova theme from master.
When I run 'hexo s' I get some errors in console.

ERROR Script load failed: themes\nova\scripts\helpers.js
Error: Cannot find module '../../../node_modules/hexo/node_modules/lodash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)

ERROR Script load failed: themes\nova\scripts\project.js
Error: Cannot find module '../../../node_modules/hexo/node_modules/lodash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)

ERROR Script load failed: themes\nova\scripts\toc.js
Error: Cannot find module '../../../node_modules/hexo/node_modules/cheerio'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)

Site runs with broken js and css.

**Comment by Jamling** [comment]
Please tell me your SW environment

**Comment by anufryieu** [comment]
Win 10 x64
node - 6.9.1
npm - 3.10.8

**Comment by Jamling** [comment]
My env node is 4.x
Please see https://github.com/Jamling/hexo-theme-nova/issues/9
